spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/reservation-service
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mvc:
    format:
      date: yyyy-MM-dd
      date-time: yyyy-MM-dd HH:mm:ss
      time: HH:mm:ss

secret:
  jwt:
    key: f827251112bb2760b2bc5a38bc0413f8d0a95b152092b4220df87a0377c51e98